version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: ./docker/django/
    # command: gunicorn showtimes.wsgi:application --workers 4 --bind 0.0.0.0:8000
    command: tail -f /dev/null
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - type: bind
        source: .
        target: /app
      - ./static:/app/static
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./docker/certbot/conf/:/etc/letsencrypt
      - ./docker/certbot/www/:/var/www/certbot
    environment:
      - CERTBOT_EMAIL=gianluca@crafture.com
      - CERTBOT_DOMAINS=-d joyride-kilroy.crafture.com,-d www.joyride-kilroy.crafture.com
    depends_on:
      - nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/certbot/conf/:/etc/nginx/ssl/:ro
      - ./docker/certbot/www/:/var/www/certbot/:ro
      - ./static:/app/static

volumes:
  db_data:
